// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;

public partial class abiturient
{
    public string gmail { get; set; }

    public string pass { get; set; }

    public string phone { get; set; }

    public string abSur { get; set; }

    public string abName { get; set; }

    public string abSecN { get; set; }

    public byte[] SNILSPhoto { get; set; }

    public byte[] passportPhoto { get; set; }

    public DateTime registrationDate { get; set; }

    public int? acieveId { get; set; }

    public int? certId { get; set; }

}