// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

public partial class abStatement
{
    public string numbState { get; set; }

    public byte[] photoState { get; set; }

    public bool freeEduc { get; set; }

    public string abGmail { get; set; }

    public string stateSt { get; set; }

    public string stateDir { get; set; }
}