// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

public partial class certificate
{
    public int idCert { get; set; }

    public byte[] photoCert { get; set; }

    public double? gpa { get; set; }
}