// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

public partial class deduct
{
    public int orderNumber { get; set; }

    public string stGmail { get; set; }

    public string grNumb { get; set; }

    public string reason { get; set; }

    public string deductDate { get; set; }
}