// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

public partial class DeletedAbiturient
{
    public string gmail { get; set; }

    public DateTime deletedDate { get; set; }

    public string abSur { get; set; }

    public string abName { get; set; }

    public string abSecN { get; set; }

    public string SNILS { get; set; }

    public string serialP { get; set; }

    public string numberP { get; set; }
}