// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

public partial class direction
{
    public string nameDir { get; set; }

    public string numbOfBudget { get; set; }

    public string numbOfNotBudget { get; set; }

    public string emplRole { get; set; }
}