// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

public partial class employee
{
    public string gmail { get; set; }

    public string empSur { get; set; }

    public string empName { get; set; }

    public string empSecN { get; set; }

    public string pass { get; set; }

    public string emplRole { get; set; }
}