// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

public partial class log
{
    public int idLog { get; set; }

    public DateTime dateoflog { get; set; }

    public TimeSpan timeoflog { get; set; }

    public string userlog { get; set; }

    public string discr { get; set; }
}