// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

public partial class mptGroup
{
    public string grNumb { get; set; }

    public string grDir { get; set; }
}