// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

public partial class ogeResult
{
    public int idRes { get; set; }

    public string points { get; set; }

    public string abGmail { get; set; }

    public string abExam { get; set; }
}