// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

public partial class parent
{
    public int idParent { get; set; }

    public string empSur { get; set; }

    public string empName { get; set; }

    public string empSecN { get; set; }

    public string phone { get; set; }

    public string stGmail { get; set; }
}