// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

public partial class payment
{
    public int idPay { get; set; }

    public string dayOfPay { get; set; }

    public string summ { get; set; }

    public string startDate { get; set; }

    public string endDate { get; set; }

    public string stGmail { get; set; }
}