// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

public partial class persAchiefe
{
    public int idAcieve { get; set; }

    public byte[] achievePhoto { get; set; }

    public int? pagesCount { get; set; }
}