// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
// using System;
using System.Collections.Generic;

public partial class stateStatus
{
    public string NameStat { get; set; }
}