// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

public partial class stGroup
{
    public int idstGroup { get; set; }

    public string stGmail { get; set; }

    public string stgroup1 { get; set; }
}