// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

public partial class student
{
    public string stGmail { get; set; }

    public string photoOMS { get; set; }

    public Boolean freeEduc { get; set; }
}